### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by tbchamp** [tbchamp/UWCSE403-Recipe-Reader#30]
settings button from recipeReader activity. -> help screen with voice commands supported and details about favorites login out details.

**Comment by tbchamp** [comment]
Anton-> app functionality
tyler-> web and text

**Comment by aosobov** [comment]
Functionality is mostly in place. Let me know when the text is ready.

**Comment by tbchamp** [comment]
written. Will get feedback tomorrow in meeting. then send to anton and add to website.
