### ISSUE TITLE
Clicking on RecipeOverview doesn't bring you to the RecipeView

### ISSUE THREAD

**Issue by ramasj** [tbchamp/UWCSE403-Recipe-Reader#40]
Not sure if this is just me but clicking on the recipes doesn't seem to do anything with the newest revision.

**Comment by kristinkarpack** [comment]
I ran into this too, wasn't sure if it was just me. Looking into it now.

**Comment by kristinkarpack** [comment]
It was my favorite-star stuff (http://mylifewithandroid.blogspot.com/2011/08/focus-problems-with-list-rows-and.html). The fix will be up within an hour.
