### ISSUE TITLE
Adding "Help" stuff I think broke the application, as I can no longer get it to run.

### ISSUE THREAD

**Issue by yamana** [tbchamp/UWCSE403-Recipe-Reader#56]

**Comment by ramasj** [comment]
Weird, I was just about to tell Anton I tried it out and it didn't seem to break anything for me.

**Comment by yamana** [comment]
Ok, maybe it's my set-up. Hold on, let me try it again.

**Comment by yamana** [comment]
Haha, nevermind, everything is fine. My bad. Carry on!
